CREATE TABLE "recipes"
(
    "id" INTEGER NOT NULL PRIMARY KEY UNIQUE,
    "name" TEXT UNIQUE,
    "minutes" TEXT,
    "calories" TEXT,
    "ingredients" TEXT,
    "recipe" TEXT
);

INSERT INTO "recipes"
VALUES (1, 'Smoked Salmon Scrambled Eggs', '10', '205', '2 large eggs; 1 ounce smoked salmon, chopped; 2 teaspoons reduced-fat cream cheese; 1 scallion, sliced', 'Lightly beat eggs in a small bowl until combined. Stir in smoked salmon, cream cheese, scallion and capers. Coat a small nonstick skillet with cooking spray and heat over medium. Add the egg mixture and cook, stirring often, until scrambled, about 3 minutes.'),
       (2, 'Banana-Cocoa Soy Smoothie', '10', '342', '1 banana; 1/2 cup silken tofu;  1/2 cup milk;  2 tablespoons unsweetened cocoa powder; 1 tablespoon honey', 'Slice banana and freeze until firm. Blend tofu, milk, cocoa and honey in a blender until smooth. With the motor running, add the banana slices through the hole in the lid and continue to puree until smooth.'),
       (3, 'Spinach & Egg Sweet Potato Toast', '20', '124', '1 large slice sweet potato; 1/2 cup cooked spinach; 1 large egg, fried or poached; 1/2 teaspoon sliced fresh chives; 1/2 teaspoon hot sauce', 'Toast sweet potato in a toaster or toaster oven until just cooked through and starting to brown, 12 to 15 minutes. Top with spinach, egg, chives and hot sauce.'),
       (4, 'Yogurt-Kiwi Cheesecake Toast', '5', '187', '2 tablespoons yogurt; 1 tablespoon cream cheese; 1 slice of bread, toasted; 1/2 kiwifruit, peeled and sliced; 1 strawberry, stems removed and sliced', 'Combine yogurt and cream cheese in a small bowl. Spread the yogurt mixture on toast and top with kiwi and strawberry.'),
       (5, 'Bagel Gone Bananas', '5', '284', '2 tablespoons natural nut butter, such as almond, cashew or peanut; 1 teaspoon honey; pinch of salt; 1 bagel, split and toasted; 1 banana, sliced', 'Stir together nut butter, honey and salt in a small bowl. Divide the mixture between bagel halves and top with banana slices.'),
       (6, 'Thermos-Ready Smoothie', '5', '276', '1 cup frozen mixed berries; 1/2 banana; 1/2 cup apple juice; 1/4 cup silken tofu', 'Combine berries, banana, apple juice and tofu in a blender; blend until smooth.'),
       (7, 'Dried Fruit Compote with Green Tea & Lemon', '105', '150', '3 green tea bags; 3 1/4 cups boiling water; 2 tablespoons sugar; 2 teaspoons freshly grated lemon zest; 3 cups mixed dried fruit, such as apples, apricots, pears, figs and/or raisins', 'Steep tea bags in boiling water for 3 to 5 minutes. Remove tea bags. Stir sugar and lemon zest into the tea. Cut any large pieces of fruit into halves or quarters. Place the fruit and tea in a 4-quart or larger slow cooker. Cover and cook until the fruit is plump and tender and the liquid is syrupy, 1 1/2 to 2 1/2 hours on high or 3 1/2 to 4 hours on low. Transfer to a bowl and let cool slightly. Cover and refrigerate until chilled.'),
       (8, 'Cherry Cream Cheese', '10', '65', '4 ounces (1/2 cup) reduced-fat cream cheese; 1/4 cup chopped pitted fresh cherries or thawed and drained frozen cherries; 11/2 teaspoons confectioners sugar; pinch of ground allspice', 'Combine cream cheese, cherries, sugar and allspice in a small bowl.'),
       (9, 'Breakfast Parfait', '10', '247', '3/4 cup low-fat cottage cheese or yogurt; 1 cup pineapple chunks, papaya chunks or cling peaches; 2 teaspoons toasted wheat germ', 'Place cottage cheese (or yogurt) in a small bowl. Top with fruit and sprinkle with wheat germ.'),
       (10, 'Raspberry-Avocado Smoothie', '5', '218', '1 avocado, peeled and pitted; 3/4 cup orange juice; 3/4 cup raspberry juice; 1/2 cup frozen raspberries, (not thawed)', 'Puree avocado, orange juice, raspberry juice and raspberries in a blender until smooth.'),
       (11, 'Pineapple-Raspberry Parfaits', '5', '155', '2 8-ounce containers (2 cups) nonfat peach yogurt; 1/2 pint fresh raspberries, (about 1 1/4 cups); 1 1/2 cups fresh, frozen or canned pineapple chunks', 'Divide and layer yogurt, raspberries and pineapple into 4 glasses.'),
       (12, 'Wake-Up Smoothie', '5', '139', '1 1/4 cups orange juice; 1 banana; 1 1/4 cups frozen berries, such as raspberries, blackberries, blueberries and/or strawberries; 1/2 cup low-fat silken tofu, or low-fat plain yogurt; 1 tablespoon sugar', 'Combine orange juice, banana, berries, tofu (or yogurt) and sugar, if using, in a blender; cover and blend until creamy. Serve immediately.'),
       (13, 'Blueberries with Lemon Cream', '10', '114', '4 ounces reduced-fat cream cheese; 3/4 cup low-fat yogurt; 1 teaspoon honey; 2 teaspoons freshly grated lemon zest; 2 cups fresh blueberries', 'Using a fork, break up cream cheese in a medium bowl. Drain off any liquid from the yogurt; add yogurt to the bowl along with honey. Using an electric mixer, beat at high speed until light and creamy. Stir in lemon zest. Layer the lemon cream and blueberries in dessert dishes or wineglasses. If not serving immediately, cover and refrigerate for up to 8 hours.'),
       (14, 'Banana-Berry Smoothie', '5', '135', '1 1/4 cups orange juice; 1 banana, peeled and sliced; 1 cup frozen blueberries, blackberries or raspberries; 1/2 cup silken tofu; 2 ice cubes, crushed; 1 tablespoon sugar', 'Combine orange juice, banana, berries, tofu and crushed ice in a blender; cover and blend until smooth and frothy. Sweeten with sugar, if desired. Serve immediately.'),
       (15, 'Fruit & Yogurt Smoothie', '10', '279', '3/4 cup nonfat plain yogurt; 1/2 cup fruit juice (apple, orange, raspberry); 1 1/2 cups (6 1/2 ounces) frozen fruit, such as blueberries, raspberries, pineapple or peaches', 'Puree yogurt with juice in a blender until smooth. With the motor running, add fruit through the hole in the lid and continue to puree until smooth.'),
       (16, 'Mexi-Melt', '10', '124', '2 tablespoons canned nonfat refried beans; 1 slice bread, toasted; 1 tablespoon prepared salsa; 1 tablespoon shredded cheese', 'Spread beans on toast. Top with salsa, then cheese. Microwave on High until the cheese is melted and the beans are hot, about 45 seconds.'),
       (17, 'Quick Breakfast Taco', '15', '239', '2 tortillas; 1 tablespoon salsa; 2 tablespoons shredded Cheddar cheese; 3 eggs', 'Top tortillas with salsa and cheese. Heat in the microwave until the cheese is melted, about 30 seconds. Meanwhile coat a small nonstick skillet with cooking spray. Heat over medium heat, add eggs and cook, stirring, until the eggs are cooked through, about 90 seconds. Divide the scrambled egg between the tacos.'),
       (18, 'Muesli with Raspberries', '5', '287', '1/3 cup muesli; 1 cup raspberries; 3/4 cup milk', 'Top muesli with raspberries and serve with milk.'),
       (19, 'Florentine Hash Skillet', '10', '226', '1 teaspoon olive oil; 1/2 cup precooked shredded potatoes; 1/2 cup frozen chopped spinach; 1 egg; pinch of salt; pinch of freshly ground pepper; 2 tablespoons shredded sharp Cheddar cheese', 'Heat oil in a small nonstick skillet over medium heat. Layer potatoes and spinach into the pan. Crack egg on top and sprinkle with salt, pepper and cheese. Cover, reduce heat to medium-low and cook until the potatoes are starting to brown on the bottom, the egg is set and the cheese is melted, 4 to 7 minutes.'),
       (20, 'Rise and Shine Parfait', '15', '259', '4 cups fat-free yogurt; 2 peaches, chopped; 2 cups fresh blackberries; 1/2 cup granola', 'Layer half of the yogurt, peaches, blackberries and granola into 4 parfait glasses. Repeat layers.'),
       (21, 'Good Old Fashioned Pancakes', '20', '158', '1 1/2 cups flour; 3 1/2 teaspoons baking powder; 1 teaspoon salt; 1 tablespoon sugar; 1 1/4 cups milk; 1 egg; 3 tablespoons butter, melted', 'In a large bowl, sift together the flour, baking powder, salt and sugar. Make a well in the center and pour in the milk, egg and melted butter; mix until smooth. Heat a lightly oiled griddle or frying pan over medium high heat. Pour or scoop the batter onto the griddle, using approximately 1/4 cup for each pancake. Brown on both sides and serve hot.'),
       (22, 'French Crepes', '35', '94', '1 cup flour; 1 teaspoon sugar; 1/4 teaspoon salt; 3 eggs; 2 cups milk; 2 tablespoons butter, melted', 'Sift together flour, sugar and salt; set aside. In a large bowl, beat eggs and milk together with an electric mixer. Beat in flour mixture until smooth; stir in melted butter. Heat a lightly oiled griddle or frying pan over medium high heat. Pour or scoop the batter onto the griddle, using approximately 2 tablespoons for each crepe. Tip and rotate pan to spread batter as thinly as possible. Brown on both sides and serve hot.'),
       (23, 'Baked Omelet Roll', '25', '206', '6 eggs; 1 cup milk; 1/2 cup flour; 1/2 teaspoon salt; 1/4 teaspoon ground black pepper; 1 cup shredded Cheddar cheese', 'Preheat oven to 450 degrees F (230 degrees C). Lightly grease a 9x13 inch baking pan. In a blender, combine eggs, milk, flour, salt and pepper; cover and process until smooth. Pour into prepared baking pan. Bake in preheated oven until set, about 20 minutes. Sprinkle with cheese. Carefully loosen edges of omelet from pan. Starting from the short edge of the pan, carefully roll up omelet. Place omelet seam side down on a serving plate and cut into 6 equal sized pieces.'),
       (24, 'Ultimate French Toast', '20', '209', '4 eggs; 2 tablespoons milk; 1/4 teaspoon ground cinnamon; 8 slices bread', 'Combine eggs, milk and cinnamon; beat well. Dip bread into egg mixture until completely coated. Heat a lightly oiled griddle or frying pan over medium high heat. Cook bread slices until they are golden brown on both sides. Serve hot.'),
       (25, 'Oven Baked Omelet', '40', '185', '1 teaspoon butter; 9 eggs; 1/2 cup sour cream; 1/2 cup milk; 1 teaspoon salt; 2 green onions, chopped; 1/4 cup shredded Cheddar cheese', 'Preheat oven to 350 degrees F (175 degrees C). Grease an 8x8-inch baking dish with butter. Beat eggs, sour cream, milk, and salt in a bowl until blended. Stir in green onions. Pour mixture in the prepared baking dish. Bake in the preheated oven until set, 25 to 30 minutes. Sprinkle Cheddar cheese over eggs and continue baking until cheese is melted, 2 to 3 minutes more.'),
       (26, 'Piggy Wiggys', '25', '317', '1 (10 ounce) can refrigerated crescent roll dough; 1 (16 ounce) package cocktail sausages', 'Preheat oven to 375 degrees F (190 degrees C). Lightly grease a large baking sheet. Separate crescent rolls. Flatten rolls and cut into triangles which measure 1 1/2 inches on each side. Wrap each sausage in a triangle of dough. Place on prepared baking sheet. Bake in preheated oven for 15 minutes, until golden.'),
       (27, 'Early Morning Oven Roasted New Potatoes', '30', '229', '1 kg potatoes, cut into wedges; 4 tablespoons butter; 2 teaspoons fresh rosemary; salt and pepper to taste', 'Preheat oven to 450 degrees F (230 degrees C). In a hot skillet, melt the butter. Stir in rosemary, salt and pepper. Coat potatoes evenly with the melted butter. Arrange the potatoes in a single layer on a baking pan. Bake in a preheated oven until potatoes are golden brown, approximately 20 to 25 minutes. Toss them occasionally to ensure that they brown on all sides.'),
       (28, 'Easy Potato Pancakes', '20', '365', '5 potatoes, peeled and shredded; 2 eggs, beaten; 1 onion, finely chopped; 3 tablespoons flour; salt and pepper to taste; 3 tablespoons olive oil', 'In a large bowl, stir together potatoes, eggs, onion, flour, salt and pepper. In a large skillet, heat oil over medium high heat. Drop large spoonfuls of the potato batter into the skillet and flatten cakes slightly with a spatula. Cook for about 4 minutes on each side, until golden brown. Serve immediately.'),
       (29, 'Avocado Toast', '10', '170', '4 slices bread; 1 avocado, halved and pitted; 2 tablespoons chopped fresh parsley; 1 1/2 teaspoons olive oil ; 1/2 lemon, juiced; 1/2 teaspoon salt; 1/2 teaspoon ground black pepper; 1/2 teaspoon onion powder; 1/2 teaspoon garlic powder', 'Toast bread in a toaster or toaster oven. Scoop avocado into a bowl. Add parsley, olive oil, lemon juice, salt, pepper, onion powder, and garlic powder; mash together using a potato masher. Spread avocado mixture into each piece of toast.'),
       (30, 'Black Bean Breakfast Bowl', '15', '625', '2 tablespoons olive oil; 4 eggs, beaten; 1 can beans, drained and rinsed; 1 avocado, peeled and sliced; 1/4 cup salsa; salt and ground black pepper to taste', 'Heat olive oil in a small pan over medium heat. Cook and stir eggs until eggs are set, 3 to 5 minutes. Place black beans in a microwave-safe bowl. Heat on High in the microwave until warm, about 1 minute. Divide warmed black beans between two bowls. Top each bowl with scrambled eggs, avocado, and salsa. Season with salt and black pepper.');



